version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_development
    ports:
      - 5432:5432

  backend:
    image: yolkai/backend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_development
    ports:
      - 3333:3333
    depends_on:
      - postgres

  frontend:
    image: yolkai/frontend
    ports:
      - 4200:4200
